<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'For the moment, only GSM numbers from Turkey are accepted. You have to enter your GSM number in this format: (555) 123 45 67' => 
        'Şu anda sadece Türkiye\'den GSM numaraları kabul edilmektedir. GSM numaranızı bu formatta girmelisiniz: (555) 123 45 67',
    'I forgot my password.' => 'Parolamı unuttum.',
    'My GSM not accepted.' => 'Telefonum kabul edilmedi.',
    'You do not need a password to login. You can use SMS, Link or Other methods. If you want, you can easily set a password after logging in.' => 
        'Giriş yapmak için bir parolaya ihtiyaç yoktur. SMS, Link veya Diğer yöntemleri kullanarak giriş yapabilirsiniz. Giriş yaptıktan sonra parola belirleyebilirsiniz.',
];
